### ISSUE TITLE
Script not enqueued properly

### ISSUE THREAD

**Issue by eriktdesign** [jordesign/wp-tithely#1]
https://github.com/jordesign/wp-tithely/blob/90341016d28a76876bcf1d271502a1ff5a2299c8/wp-tithely.php#L188

Unless I'm missing something, the script isn't being properly enqueued with this line. I can't see the script handle "tithely" being defined elsewhere.

See: https://developer.wordpress.org/reference/functions/wp_enqueue_script/

However, it probably shouldn't be defined in this scope. It should be in a function called on the action `wp_enqueue_scripts` --

```
function wp_tithely_enqueue_script() {
	wp_enqueue_script( "tithely", array(), '20171113', true );
	wp_add_inline_script( "tithely_init", "var tw = create_tithely_widget();" );
}

add_action( 'wp_enqueue_scripts', 'wp_tithely_enqueue_script' );
```

I've also added the `create_tithely_widget()` call in this block. WordPress will then inline that line of script after it outputs the Tithely script. I've left the "dependencies" array empty on the enqueue call, but if the tithely script requires jQuery, you'll want to have it in that array -- `array( "jquery" )`.

Once you have the enqueue working properly, you can remove the script blocks from the shortcode and widget functions.

Note: I haven't tested this, but if you want I can do a pull request.

**Comment by jordesign** [comment]
That's awesome - thanks @eriktdesign 
It was originally queued correctly but the inline script was failing.
Hadn't thought of including it in the same call - but that's working beautifully. Thanks heaps
